insert into web_admin_options values ('SPIORD', 'admin_flag', 'Administrator Flag - Is this person an administrator?', 'YN', '')
insert into web_admin_options values ('SPIORD', 'user_maint_flag', 'User Maintenance Flag - Can this user modify user settings?', 'YN', '')
insert into web_admin_options values ('SPIORD', 'profile_flag', 'Profile Flag - Can this person update the ETS Profile?', 'YN', '')
insert into web_admin_options values ('SPIORD', 'disclaim_flag', 'Disclaimer Flag - Can this person update ETS Disclaimers?', 'YN', '')
insert into web_admin_options values ('SPIORD', 'block_flag', 'Block Flag - Block this user from using Employee Timesheets?', 'YN', '')