
BEGIN TRANSACTION
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SET QUOTED_IDENTIFIER ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET XACT_ABORT ON
COMMIT TRANSACTION
GO

CREATE DATABASE [eFPAuthProvider]
ON PRIMARY
(   NAME=N'eFPAuthProvider', 
    FILENAME=N'eFPAuthProviderDATALOC\eFPAuthProvider.mdf', 
    SIZE=14MB, 
    FILEGROWTH=1MB)
LOG ON 
(   NAME=N'eFPAuthProvider_log', 
    FILENAME=N'eFPAuthProviderLOGLOC\eFPAuthProvider_log.ldf', 
    SIZE=195MB, 
    MAXSIZE=2097152MB, 
    FILEGROWTH=10%)
COLLATE SQL_Latin1_General_CP1_CI_AS
GO